
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  

      - name: "Login to Docker hub"
        run: docker login --username fathyelghazaly --password dckr_pat_XKjwCy-vNjKzG4zypmLwmTm1g_E

      - name: "Building Docker Image"
        run: docker build -t fathyelghazaly/image .
      
      - name: "Pushing to Docker hub"
        run: docker push fathyelghazaly/image
